In [2]:
import numpy as np
list1 = [2, 4, 6, 8]
array1 = np.array(list1)
array1

array([2, 4, 6, 8])

In [3]:
import numpy as np
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [4]:
import numpy as np
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [6]:
array1 = np.arange(5)
print("Using np.arange(5):", array1)
# create an array with values from 1 to 8 with a step of 2
array2 = np.arange(1, 9, 2)
print("Using np.arange(1, 9, 2):",array2)

Using np.arange(5): [0 1 2 3 4]
Using np.arange(1, 9, 2): [1 3 5 7]


In [9]:
import numpy as np
# generate an array of 5 random numbers
array1 = np.random.rand(5)
print(array1)

[0.83690195 0.4019023  0.94407662 0.05353671 0.61914839]


In [10]:
import numpy as np
# Example 1: Creation of 1D array
arr1=np.array([10,20,30])
print("My 1D array:\n",arr1)

My 1D array:
 [10 20 30]


In [11]:
arr2 = np.array([[10,20,30],[40,50,60]])
print("My 2D numpy array:\n", arr2)

My 2D numpy array:
 [[10 20 30]
 [40 50 60]]


In [12]:
arr= np.arange(0, 20, 3)
print ("A sequential array with steps of 3:\n", arr)

A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


In [13]:
arr= np.linspace(0, 3, 5)
print ("A sequential array with 5 values between 0 and 5:\n", arr)

A sequential array with 5 values between 0 and 5:
 [0.   0.75 1.5  2.25 3.  ]


In [14]:
arr = np.ones((2,3))
print("numpy array:\n", arr)
print("Type:", type(arr))

numpy array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Type: <class 'numpy.ndarray'>


In [15]:
import numpy as np
# create an array of  integers
int_array = np.array([-3, -1, 0, 1])
# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])
# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])
# check the data type of int_array
print(int_array.dtype)  # prints int64
# check the data type of float_array
print(float_array.dtype)  # prints float64
# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

int64
float64
complex128


In [16]:
import numpy as np
# create an array of 8-bit integers
array1 = np.array([1, 3, 7], dtype='int8')
# create an array of unsigned 16-bit integers
array2 = np.array([2, 4, 6], dtype='uint16')
# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')
# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')
# print the arrays and their data types
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


In [17]:
import numpy as np
# create an array of integers
int_array = np.array([1, 3, 5, 7])
# convert data type of int_array to float
float_array = int_array.astype('float')
# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


In [18]:
import numpy as np
# create a 2-D array 
array1 = np.array([[2, 4, 6],
                  [1, 3, 5]])
# check the dimension of array1
print(array1.ndim)

2


In [19]:
import numpy as np
array1 = np.array([[1, 2, 3],
                 [6, 7, 8]])
# return total number of elements in array1
print(array1.size)

6


In [21]:
import numpy as np
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])
array1

array([[1, 2, 3],
       [6, 7, 8]])

In [22]:
import numpy as np
# create an array of integers 
array1 = np.array([6, 7, 8])
# check the data type of array1
print(array1.dtype)

int64


In [23]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])
# create a 1-D array of 32-bit integers 
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)  # prints 8
print(array2.itemsize)  # prints 4

8
4


In [25]:
import numpy as np
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x000002D4B92687C0>
Data of array2 is:  <memory at 0x000002D4B927CFB0>


In [27]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("Original matrices:")
print(p)
print(q)
# Perform matrix multiplication using np.dot
result1 = np.dot(p, q)
print("Result of the matrix multiplication:")
print(result1)

Original matrices:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the matrix multiplication:
[[1 2]
 [3 4]]


In [29]:
import numpy as np
from numpy import linalg as LAD
a = np.array([[1, 0], [1, 2]])
# Display the original 2x2 array 'a'
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [30]:
#a.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [31]:
#b.Write a NumPy program to reverse an array (the first element becomes the last).
reversed_array = np.flip(matrix)
print(reversed_array)


[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


In [32]:
#c.Write a NumPy program to find common values between two arrays.
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
print(common_values)


[4 5]


In [33]:
#d.Write a NumPy program to repeat array elements.
array = np.array([1, 2, 3])
repeated_array = np.repeat(array, 2)
print(repeated_array)


[1 1 2 2 3 3]


In [34]:
#e.Write a NumPy program to find the memory size of a NumPy array.
array = np.array([1, 2, 3])
memory_size = array.nbytes
print(memory_size)


24


In [35]:

#f.Write a NumPy program to create an array of ones and zeros.
ones_array = np.ones((3, 3))
zeros_array = np.zeros((3, 3))
print(ones_array)
print(zeros_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
#g.Write a NumPy program to find the 4th element of a specified array.
array = np.array([10, 20, 30, 40, 50])
fourth_element = array[3]
print(fourth_element)

40
